environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run unit

build: "off"

version: "{build}"
